# Generated by Django 5.0.4 on 2024-05-19 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr_system', '0003_worksession'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeprofile',
            name='hourly_rate',
            field=models.FloatField(default=0),
        ),
    ]
